---
jetbrains_toolbox_install: false
jetbrains_toolbox_arch_map:
  x86_64: linux
  amd64: linux
  aarch64: linuxArm64
  arm64: linuxArm64
jetbrains_toolbox_download_url: "https://download.jetbrains.com/toolbox/jetbrains-toolbox-3.1.0.63220.tar.gz"
jetbrains_toolbox_checksum: ""
