---
chezmoi_apply: false
chezmoi_repo: "{{ lookup('env', 'DOTFILES_REPO') | default('https://github.com/Beta-Techno/dotfiles.git', true) }}"
chezmoi_bin_path: "{{ lookup('env','HOME') | default(ansible_env.HOME, true) + '/.local/bin/chezmoi' }}"
